name: Migrate Images to R2

on:
  schedule:
    - cron: '0 */12 * * *' # 每12小时执行

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Run migrate API
        run: |
          curl -X GET "https://heysimo.com/api/migrate-images?key=${{ secrets.MIGRATE_CRON_KEY }}"
